### ISSUE TITLE
Add new logo for header and footer

### ISSUE THREAD

**Issue by hiteshahuja23** [morrisjames/morrisjames.github.io#21]

**Comment by hiteshahuja23** [comment]
<img width="163" alt="check" src="https://user-images.githubusercontent.com/61080698/85600278-f0be1880-b66a-11ea-8f19-2234e755571b.png">

**Comment by hiteshahuja23** [comment]
UPDATE TAGLINE TO : "Health is a gift of life"

**Comment by piyushnanwani** [comment]
https://github.com/morrisjames/morrisjames.github.io/pull/24
