### ISSUE TITLE
Update "Products" dropdown in Navbar

### ISSUE THREAD

**Issue by hiteshahuja23** [morrisjames/morrisjames.github.io#22]
- Hospital 

1. Beds
2. Pillows
3. Furniture
4. Mattresses
5. Others

- Medical Devices

- Consumables & Accessories

**Comment by piyushnanwani** [comment]
Hi Hitesh!
 
I wanted to know the progress of this issue and the amount of time required to complete it.

Thanks
Piyush

**Comment by hiteshahuja23** [comment]
Hi Piyush,

It will be done by eod.

Regards,
Hitesh

**Comment by hiteshahuja23** [comment]
Hi Piyush,

I have pushed the changes to the branch "update-dropdown".
You can check once and if okay, you can push to the master and close the issue.

Regards,
Hitesh

**Comment by piyushnanwani** [comment]
I have checked it and everything is perfect!

**Comment by piyushnanwani** [comment]
https://github.com/morrisjames/morrisjames.github.io/pull/30
