### ISSUE TITLE
Modifications in slide show of home page

### ISSUE THREAD

**Issue by morrisjames** [morrisjames/morrisjames.github.io#3]
-> Atleast 5 Images : displaying our various products
-> Add a text as a caption on top of each image describing the type of image 

NOTE : Size of images should be exactly same as of the first image of the present slide show

**Comment by hiteshahuja23** [comment]
Check karliyo bro "update-carousel" branch main and then merge to master!

**Comment by hiteshahuja23** [comment]
@piyushnanwani

**Comment by piyushnanwani** [comment]
Hi @hiteshahuja23 
I checked and also slightly modified the carousel-caption. I added a background-color layer to the caption.

**Comment by piyushnanwani** [comment]
Merged to master https://github.com/morrisjames/morrisjames.github.io/pull/44

**Comment by piyushnanwani** [comment]
Hi @hiteshahuja23 
Please check the color layer added in the 3rd and 4th image and tell if any change should be made or not

**Comment by hiteshahuja23** [comment]
No @piyushnanwani I think it looks good. No modifications required.

**Comment by piyushnanwani** [comment]
Okay!
