### ISSUE TITLE
Add content in furniture product page

### ISSUE THREAD

**Issue by morrisjames** [morrisjames/morrisjames.github.io#5]
Following things must be added in the page : 

-> A related image just below navigation bar
-> Add various types furniture [Use bootstrap grid layout to arrange these items ]

**Comment by piyushnanwani** [comment]
[2 ] Add various types furniture [Use bootstrap grid layout to arrange these items ] - Done 

https://github.com/morrisjames/morrisjames.github.io/pull/17
